### ISSUE TITLE
Binary files in the DIID sources

### ISSUE THREAD

**Issue by BastianTeufel-GTR** [NickHodges/NickBookCode#1]
Hi Nick,

I'm currently working through your great "Dependency Injection" book.
Thanks for sharing your knowledge about this topic in a great easy to understand and good to read way.

While looking up and downloading the sample source code in your repo I found that you have also commited a lot of DCU files along with the sample code - in DIID/FileViewer/Win32/Debug

I think it should be save to remove it and so reduce the source code amount by approx. 20MB 😄

**Comment by NickHodges** [comment]
Hey, thanks for letting me know!  Not good. 

Should be fixed.  Please confirm....

**Comment by BastianTeufel-GTR** [comment]
It looks good now, thanks 👍
